#!/usr/bin/env bash

# Inspired on https://github.com/adriancooney/Taskfile

set -e

function help {
  echo "$0 <task> <args>"
  echo "Tasks:"
  compgen -A function | cat -n
}

function default {
  help
}

function tableplus {
    open -a TablePlus ./database/database.sqlite
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-default}"
